apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  namespace: default
  labels:
    app: testing
spec:
  containers:
  - name: producer
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /producer
      name: share-volume
    args:
    - /bin/sh
    - -c
    - echo "hello world" > /producer/hello; sleep 30000

  - name: consumer
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /consumer
      name: share-volume
    args:
    - /bin/sh
    - -c
    - cat /consumer/hello; sleep 30000
  restartPolicy: Always
  volumes:
  - name: share-volume
    emptyDir: {}
