apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: default
  labels:
    app: pv-testing
spec:
  containers:
  - name: mypod1
    image: busybox
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - sleep 30000
    volumeMounts:
    - mountPath: "/mydata"
      name: mydata
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: mypvc1
